
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { '' } %> # 

development:
  <<: *default
  database: new_app_development

test:
  <<: *default
  database: new_app_test

production:
  <<: *default
  database: new_app_production
  username: new_app
  password: <%= ENV["NEW_APP_DATABASE_PASSWORD"] %>
